---
# global lables
labels: {}

# global annotations
annotations: {}


serviceAccountName: trivy

imagePullSecrets: []
# - secret-name

deployment:
  replicas: 1
  # labels to add for matchLabels
  selectorLabels:
    app.kubernetes.io/part-of: staging

  strategy:
    type: Recreate
    maxSurge: 1
    maxUnavailable: 0

  redis:
    resources:
      requests:
        memory: 256Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 100m
    config: |-
      protected-mode yes 
      port 6379
      save ""
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      runAsUser: 999
      runAsGroup: 999
      capabilities:
        drop:
        - ALL
    livenessProbe: true
    readinessProbe: true
    image: redis:bullseye@sha256:0d9c9aed1eb385336db0bc9b976b6b49774aee3d2b9c2788a0d0d9e239986cb3

  trivy:
    # proxy:
    #   http: http://squid.proxy.svc.cluster.local:3128
    #   https: http://squid.proxy.svc.cluster.local:3128

    ingress:
      enable: true
      tls:
        enable: true
        secretName: trivy-tls
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: self
      labels: {}
      host: trivy.yaser.linux
    service:
      port: 4954
      type: ClusterIP
      #type: NodePort
      #nodePort: 300025

    # Trivy authentication token and token header name
    # by default a random token will get generated.
    #token: secret123
    #tokenName: trivy-token

    image: yaskinny/trivy:0.23.0@sha256:e5daab9097ca3fdd3c4123a747571c6d78e77988ff76bfa585f2326564194e12
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 9000
      runAsGroup: 9000
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
    livenessProbe: true
    readinessProbe: true
    resources:
      requests:
        memory: 250Mi
        cpu: 150m
      limits:
        memory: 512Mi
        cpu: 350m
networkPolicy:
  allowIngress:
  - namespace: cicd
    extraLabels:
      app.kubernetes.io/part-of: cicd
  enable: true
  ingressController:
    # namespace which your ingress controller is deployed
    namespace: ingress-nginx
    extraLabelsForIngress:
      app.kubernetes.io/component: controller
...