FROM golang:alpine@sha256:519c827ec22e5cf7417c9ff063ec840a446cdd30681700a16cf42eb43823e27c as build
RUN apk add ca-certificates git && \
  mkdir /tmp/this && \
  git clone https://github.com/aquasecurity/trivy --depth=1 --single-branch --branch=main /trivy && \
  cd /trivy && \
  CGO_ENABLED=0 go build -o bin/trivy cmd/trivy/main.go
FROM scratch
COPY --chown=9000 --from=build /tmp/this /tmp
COPY --from=build /trivy/bin/trivy /trivy
COPY --from=build /etc/ssl/certs /etc/ssl/certs
USER 9000
ENTRYPOINT ["/trivy","server"]