---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-trivy
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  TRIVY_DEBUG: "false"
  TRIVY_LISTEN: "0.0.0.0:{{ .Values.deployment.trivy.service.port }}"
  TRIVY_SKIP_UPDATE: "false"
  TRIVY_CACHE_DIR: '/tmp'
  TRIVY_CACHE_BACKEND: 'redis://localhost:6379'
  redisConfig: |-
    {{- .Values.deployment.redis.config | nindent 4}}
... 