---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-trivy
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- if .Release.IsInstall }}
  TRIVY_TOKEN: "{{ default (randAlphaNum 25) .Values.deployment.trivy.token | b64enc }}"
  TRIVY_TOKEN_HEADER: "{{ default "Trivy-Token" .Values.deployment.trivy.tokenName | b64enc }}"
{{- else  }}
  TRIVY_TOKEN: "{{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-trivy" .Release.Name )).data "TRIVY_TOKEN" }}"
  TRIVY_TOKEN_HEADER: "{{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-trivy" .Release.Name )).data "TRIVY_TOKEN_HEADER" }}"
{{- end }}
...